#ifndef _HTTP_DATA_H_
#define _HTTP_DATA_H_

static const char _http_err404_page[] = \
	"<html>\n"
	"	<head>\n"
	"	<title>Error 404: Element not found</title>\n"
	"	</head>\n"
	"	\n"
	"	<body style=\"background-color:#29242A; color:#FFFFFF; font-family:'HelveticaNeue-Light','Helvetica Neue Light','Helvetica Neue','Ubuntu-Title','Helvetica','Droid Sans','Verdana';\">\n"
	"	<table border=\"0\" height=\"100%\" width=\"100%\"><tr><td align=center valign=center>\n"
	"	<table border=\"0\">"
	"		<tr>\n"
	"			<td style=\"align:center; vertical-align:middle;\">\n"
	"				<div style=\"font-size:500%; text-shadow:black 3px 2px 5px; text-align:center;\">\n"
	"					?!\n"
	"				</div>\n"
	"			</td>\n"
	"			<td>\n"
	"				&nbsp;&nbsp;&nbsp;\n"
	"		</td>\n"
	"			<td style=\"align:left; vertical-align:middle;\">\n"
	"				<div style=\"font-size:150%; text-shadow:black 3px 2px 5px;\">\n"
	"					Oops...\n"
	"				</div>\n"
	"				<br>\n"
	"				Sorry, element not found.<br>\n"
	"				Error: 404\n"
	"			</td>\n"
	"		</tr>\n"
	"	</table>\n"
	"	</tr></td></table>\n"
	"	</body>\n"
	"</html>\n";
static const size_t _htto_err404_len = sizeof(_http_err404_page) - 1;

static const char _http_err500_page[] = \
	"<html>\n"
	"	<head>\n"
	"	<title>Error 500: Internal server error</title>\n"
	"	</head>\n"
	"	\n"
	"	<body style=\"background-color:#29242A; color:#FFFFFF; font-family:'HelveticaNeue-Light','Helvetica Neue Light','Helvetica Neue','Ubuntu-Title','Helvetica','Droid Sans','Verdana';\">\n"
	"	<table border=\"0\" height=\"100%\" width=\"100%\"><tr><td align=center valign=center>\n"
	"	<table border=\"0\">"
	"		<tr>\n"
	"			<td style=\"align:center; vertical-align:middle;\">\n"
	"				<div style=\"font-size:500%; text-shadow:black 3px 2px 5px; text-align:center;\">\n"
	"					XX\n"
	"				</div>\n"
	"			</td>\n"
	"			<td>\n"
	"				&nbsp;&nbsp;&nbsp;\n"
	"		</td>\n"
	"			<td style=\"align:left; vertical-align:middle;\">\n"
	"				<div style=\"font-size:150%; text-shadow:black 3px 2px 5px;\">\n"
	"					Oops...\n"
	"				</div>\n"
	"				<br>\n"
	"				An unexpected internal server error happend.<br>\n"
	"				Please try it again.\n"
	"				Error: 500\n"
	"			</td>\n"
	"		</tr>\n"
	"	</table>\n"
	"	</tr></td></table>\n"
	"	</body>\n"
	"</html>\n";
static const size_t _htto_err500_len = sizeof(_http_err500_page) - 1;

#endif /* _HTTP_DATA_H_ */
