###################
# General
###################
MCCFLAGS					+= -I.
MCCFLAGS					+= -DCONFIG_BANNER_VERSION="\"MiniCache/$(GITSHA1)/$(ARCH)\""
MCCFLAGS-$(CONFIG_MINICACHE_HIDE_BANNER)	+= -DCONFIG_HIDE_BANNER
MCCFLAGS-$(CONFIG_MINICACHE_AUTOMOUNT)		+= -DCONFIG_AUTOMOUNT
MCCFLAGS-$(CONFIG_MINICACHE_MINDER_PRINT)	+= -DCONFIG_MINDER_PRINT
MCCFLAGS-$(CONFIG_MINICACHE_DEBUG_PRINT)	+= -DCONFIG_DEBUG_PRINT
MCCFLAGS-$(CONFIG_MINICACHE_TRACE_BOOTTIME)	+= -DTRACE_BOOTTIME
MCCFLAGS-$(CONFIG_MINICACHE_IPERF_SERVER)	+= -DIPERF_SERVER

MCOBJS						= ring.o \
						  mempool.o \
						  hexdump.o \
						  debug.o \
						  htable.o \
						  shfs.o \
						  shfs_check.o \
						  shfs_cache.o \
						  shfs_fio.o \
						  shfs_tools.o \
						  http_parser.o \
						  http_fio.o \
						  http_link.o \
						  http.o \
						  link_format.o \
						  minicache.o
ifeq ($(CONFIG_MINICACHE_IPERF_SERVER),y)
MCOBJS						+= iperf.o
endif

MCCFLAGS-$(CONFIG_HTABLE_DEBUG)			+= -DHTABLE_DEBUG
MCCFLAGS-$(CONFIG_MEMPOOL_DEBUG)		+= -DMEMPOOL_DEBUG


######################################
## µSh
######################################
ifeq ($(CONFIG_SHELL),y)
MCCFLAGS	+= -DSHELL_INFO="\"MiniCache/$(GITSHA1)/$(ARCH) (built: $(shell date +%F))\nCopyright(C) 2013-2016 NEC Europe Ltd.\"" \
		   -DSHELL_WELCOME="\"MiniCache $(GITSHA1)\nCopyright(C) 2013-2016 NEC Europe Ltd.\n\nType 'help' to get an overview of available commands\""

ifeq ($(CONFIG_SHELL_COLORPROMPT),y)
MCCFLAGS	+= -DSHELL_PROMPT="\"\\e[01;31mmc\\e[00m\#\""
else
MCCFLAGS	+= -DSHELL_PROMPT="\"mc\#\""
endif

MCOBJS		+= shell.o shell_extras.o
MCCFLAGS	+= -DHAVE_SHELL
endif
MCCFLAGS-$(CONFIG_SHELL_DEBUG)		+= -DSHELL_DEBUG

######################################
## ctldir (only available on Mini-OS)
######################################
ifeq ($(TARGET),minios)
MCCFLAGS-$(CONFIG_CTLDIR)		+= -DHAVE_CTLDIR
MCCFLAGS-$(CONFIG_CTLDIR_NOCHMOD)	+= -DCTLDIR_NOCHMOD
MCCFLAGS-$(CONFIG_CTLDIR_DEBUG)	+= -DCTLDIR_DEBUG
MCOBJS-$(CONFIG_CTLDIR)		+= target/$(TARGET)/ctldir.o
endif

######################################
## SHFS
######################################
MCCFLAGS-$(CONFIG_SHFS_OPENBYNAME)	+= -DSHFS_OPENBYNAME
MCCFLAGS-$(CONFIG_SHFS_CACHEINFO)	+= -DSHFS_CACHE_INFO
MCCFLAGS-$(CONFIG_SHFS_DEBUG)		+= -DSHFS_DEBUG
MCCFLAGS-$(CONFIG_SHFS_CACHE_DEBUG)	+= -DSHFS_CACHE_DEBUG
MCCFLAGS-$(CONFIG_SHFS_CACHE_DISABLE)	+= -DSHFS_CACHE_DISABLE
MCCFLAGS-$(CONFIG_SHFS_CACHE_STATS)	+= -DSHFS_CACHE_STATS
ifeq ($(CONFIG_SHFS_STATS),y)
MCCFLAGS				+= -DSHFS_STATS
MCOBJS					+= shfs_stats.o
ifeq ($(CONFIG_SHFS_STATS_HTTP),y)
MCCFLAGS				+= -DSHFS_STATS_HTTP
#ifeq ($(shell echo ${CONFIG_SHFS_STATS_HTTP_DPCR}\>=2 | bc),"1")
MCCFLAGS				+= -DSHFS_STATS_HTTP_DPC \
					   -DSHFS_STATS_HTTP_DPCR=$(CONFIG_SHFS_STATS_HTTP_DPCR)
#endif
endif
endif

ifneq ($(CONFIG_SHFS_CACHE_READAHEAD),)
CONFIG_SHFS_CACHE_READAHEAD		?= 8
MCCFLAGS				+= -DSHFS_CACHE_READAHEAD=$(CONFIG_SHFS_CACHE_READAHEAD)
endif
CONFIG_SHFS_CACHE_POOL_NB_BUFFERS	?= 64
MCCFLAGS-$(CONFIG_SHFS_CACHE_POOL_MAXALLOC) += -DSHFS_CACHE_POOL_MAXALLOC
ifneq ($(CONFIG_SHFS_CACHE_POOL_MAXALLOC_THRESHOLD),)
MCCFLAGS-$(CONFIG_SHFS_CACHE_POOL_MAXALLOC) += -DSHFS_CACHE_POOL_MAXALLOC_THRESHOLD=$(CONFIG_SHFS_CACHE_POOL_MAXALLOC_THRESHOLD)
endif
MCCFLAGS				+= -DSHFS_CACHE_POOL_NB_BUFFERS=$(CONFIG_SHFS_CACHE_POOL_NB_BUFFERS)
MCCFLAGS-$(CONFIG_SHFS_CACHE_GROW)	+= -DSHFS_CACHE_GROW

######################################
## HTTP
######################################
MCCFLAGS				+= -DHTTP_SERVER_AGENT="\"MiniCache/$(GITSHA1)\""
MCCFLAGS-$(CONFIG_HTTP_TESTFILE)	+= -DHTTP_TESTFILE
ifneq ($(CONFIG_HTTP_TESTFILE_SIZE),)
MCCFLAGS-$(CONFIG_HTTP_TESTFILE)	+= -DHTTP_TESTFILE_LEN=$(CONFIG_HTTP_TESTFILE_SIZE)
endif
MCCFLAGS-$(CONFIG_HTTP_INFO)		+= -DHTTP_INFO
MCCFLAGS-$(CONFIG_HTTP_URL_CUTARGS)	+= -DHTTP_URL_CUTARGS
MCCFLAGS-$(CONFIG_HTTP_LINK_MEMCPY)	+= -DHTTP_LINK_MEMCPY

MCCFLAGS-$(CONFIG_HTTP_DEBUG)		+= -DHTTP_DEBUG
MCCFLAGS-$(CONFIG_HTTP_DEBUG_SESSIONSTATES) += -DHTTP_DEBUG_SESSIONSTATES
MCCFLAGS-$(CONFIG_HTTP_DEBUG_PRINTACCESS) += -DHTTP_DEBUG_PRINTACCESS

######################################
## Misc
######################################
MCCFLAGS-$(CONFIG_TESTSUITE)		+= -DTESTSUITE
MCOBJS-$(CONFIG_TESTSUITE)		+= testsuite.o

######################################
MCOBJS					+= $(MCOBJS-y)
MCCFLAGS				+= $(MCCFLAGS-y)
